
export * from './autor.interface';
export * from './base-dados-api.interface';
export * from './biblioteca.interface';
export * from './colecom.interface';
export * from './editorial.interface';
export * from './estadisticas.interface';
export * from './estilos-literarios.interface';
export * from './genero.interface';
export * from './graficos.interface';
export * from './listado-autores.interface'
export * from './listado-bibliotecas.interface';
export * from './listado-colecons.interface';
export * from './listado-editoriais.interface';
export * from './listado-estilos-literarios.interface';
export * from './listado-generos.interface';
export * from './listado-livros.interface';
export * from './livro.interface';
export * from './relectura.interface';
export * from './usuario.interface';
